### ISSUE TITLE
Not working on High Sierra

### ISSUE THREAD

**Issue by patrickrushton** [rcmdnk/MenuBarGmail#2]
Works on my Mojave computer, but on High Sierra, the icon doesn't appear in the menubar.

I found this in console log for each time I tried to start the app

com.apple.xpc.launchd[1] (org.pythonmac.unspecified.MenuBarGmail.21568[2377]): Service exited due to signal: Illegal instruction: 4 sent by exc handler[0]

**Comment by rcmdnk** [comment]
The last app was compiled on (maybe) Sierra,
and it could not work on the recent macOS.
But it is strange that it works on the recent Mojave,
and does not work on High Sierra.
I've not used this app for a long time, but it was working at least on High Siera.

Maybe you can try to run the script directly
or build.

I can try to check on Catalina, but it is difficult to check on High Sierra now.
