### ISSUE TITLE
“MenuBarGmail.app” cannot be opened because the developer cannot be verified."

### ISSUE THREAD

**Issue by ibehnam** [rcmdnk/MenuBarGmail#3]
I really hate that Apple forces app signing. Is there any way to get the app working on Monterey?

**Comment by rcmdnk** [comment]
I think there are other problems to run this app on Monterey.
I tried on my Mac (Monterey), it was launched if I allow the app at Security and Privacy in Settings. 
But no icon appears in Menubar.

Sorry, I've not updated this app and not used for years.
If I remember correctly, it could not run even at previous OS versions.

It must be updated at least python version (it used obsolete python 2.x...).

**Comment by ibehnam** [comment]
Oh, thanks for letting me know. It's too bad because an app like this is good for productivity. There are alternatives, but they're closed-source and can't really trust them.

**Comment by rcmdnk** [comment]
Updated v0.2.3.

To update by homebrew:

    $ brew update
    $ brew reinstall --cask menubargmail

or 

     $ brew install rcmdnk/rcmdnkcask/menubargmail

if you have not installed it.

You can launch it from /Applicatins folder.
For the first time, you may see the warning of the security.

You can ignore it from Settings->Security and Privacy.


Could you please try and let me know if you have any trouble, yet.
